name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json  # ✅ Ensure correct dependency caching

    - name: Install dependencies
      run: npm ci
      working-directory: backend  # ✅ Run inside backend directory

    - name: Build project
      run: npm run build --if-present
      working-directory: backend  # ✅ Run inside backend directory

    - name: Setup environment file
      run: |
        touch .env
        echo "${{ secrets.PROD_ENV_FILE }}" > .env
      working-directory: backend  # ✅ Ensure .env is created inside backend folder
